/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function divide(a: number, b: number): number
export function greetings(name: string): string
